export CLIMACELL_APIKEY=xxxxxxxxxxxxxx
export GOOGLE_CALENDAR_ID=primary
export WAVESHARE_EPD75_VERSION=2

export WEATHER_FORMAT=CELSIUS
export WEATHER_LATITUDE=51.3656
export WEATHER_LONGITUDE=0.1963
